name: develop build test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup mise
      run: |
        # Install mise
        curl https://mise.jdx.dev/install.sh | sh
        
        # Update PATH for CI environment
        export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
        
        # Activate mise for the current shell
        eval "$(~/.local/bin/mise activate bash)"
        
        # Verify mise setup
        mise doctor

    - name: Install Tuist CLI  
      run: |
        # Re-export PATH and activate mise in this step
        export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
        eval "$(~/.local/bin/mise activate bash)"
        
        # Install Tuist
        mise install tuist

        # Verify Tuist installation
        tuist --version

    - name: Tuist install
      run: |
        export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
        eval "$(~/.local/bin/mise activate bash)"
        mise x -- tuist install
    
    - name: Tuist build
      run: |
        export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
        eval "$(~/.local/bin/mise activate bash)"
        mise x -- tuist build

    - name: Tuist Test
      run: |
        export PATH="$HOME/.local/bin:$HOME/.local/share/mise/shims:$PATH"
        eval "$(~/.local/bin/mise activate bash)"
        mise x -- tuist test